#!/bin/bash
# Script pour afficher tous les fichiers à créer

echo "=== MODULE CLIENTS (10 fichiers) ==="
echo "1. src/app/features/clients/clients.module.ts"
echo "2. src/app/features/clients/clients-routing.module.ts"
echo "3. src/app/features/clients/liste/liste.component.ts"
echo "4. src/app/features/clients/liste/liste.component.html"
echo "5. src/app/features/clients/liste/liste.component.scss"
echo "6. src/app/features/clients/form/form.component.ts"
echo "7. src/app/features/clients/form/form.component.html"
echo "8. src/app/features/clients/form/form.component.scss"
echo "9-10. spec files"
echo ""
echo "=== MODULE STOCKS (6 fichiers) ==="
echo "11. src/app/features/stocks/stocks.module.ts"
echo "12. src/app/features/stocks/stocks-routing.module.ts"
echo "13. src/app/features/stocks/liste/liste.component.ts"
echo "14. src/app/features/stocks/liste/liste.component.html"
echo "15. src/app/features/stocks/liste/liste.component.scss"
echo "16. spec file"
echo ""
echo "=== MODULE FOURNISSEURS (9 fichiers) ==="
echo "17-25. Similar structure..."
echo ""
echo "=== MODULE VENTES (7 fichiers) ==="
echo "26-32. Similar structure..."
echo ""
echo "=== MODULE ACHATS (7 fichiers) ==="
echo "33-39. Similar structure..."
echo ""
echo "=== DIALOG STOCK (3 fichiers) ==="
echo "40-42. stock-adjust-dialog..."
echo ""
echo "=== FICHIERS MODIFIÉS (2) ==="
echo "43. src/app/app-routing.module.ts"
echo "44. src/app/shared/shared.module.ts"
echo ""
echo "=== DOCUMENTATION (1) ==="
echo "45. README_FINAL.md"

